repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: detect-terraform-docs
  - repo: https://github.com/antonk52/pre-commit-eslint
    rev: v1.3.1
    hooks:
      - id: eslint
        stages: [commit]
        files: .js$
        args:
          - --quiet
          - --fix
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pretty-quick --staged
        language: system
        types: [python]
