repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: [--fix]
        files: '\.(jsx|tsx|js|ts)$'
        types: [javascript]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: Prettier formatting check
